sieu_thi_v1/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);
Router::Prefix('home',function($routes){
    $routes->connect('/', ['controller' => 'Pages', 'action' =>'home']);
    $routes->connect('/san-pham/', ['controller' => 'Products', 'action' =>'index']);
    $routes->connect('/:slug/:id', ['controller' => 'Products', 'action' =>'single'],['pass'=>['slug','id']]);
    $routes->connect('/products/add-cart/:id', ['controller' => 'Products', 'action' =>'add_Cart'],['pass'=>['id']]);
    $routes->connect('/:slug', ['controller' => 'Products', 'action' =>'index'],['pass'=>['slug']]);
    $routes->connect('/gio-hang', ['controller' => 'Cart', 'action' =>'index']);
    $routes->connect('/admin', ['controller' => 'Admin', 'action' =>'index']);

});

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/', ['controller' => 'Users', 'action' => 'index']);
    $routes->connect('/admin', ['controller' => 'Users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

sieu_thi_v1/src/Model/Table/ProductsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;


class ProductsTable extends Table
{

    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('products');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id'
        ]);
        $this->hasMany('OrderProducts', [
            'foreignKey' => 'product_id'
        ]);
        $this->hasMany('ProductMetas', [
            'foreignKey' => 'product_id'
        ])->setJoinType('INNER');
    }

   
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('name', 'create')
            ->notEmpty('name');

        $validator
            ->allowEmpty('avatar');

        $validator
            ->allowEmpty('price_in')
            ->notEmpty('price_in');


        $validator
            ->allowEmpty('price_out')
            ->notEmpty('price_out');

        $validator
            ->integer('status')
            ->requirePresence('status', 'create')
            ->notEmpty('status');

        return $validator;
    }

    
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['category_id'], 'Categories'));

        return $rules;
    }
}

sieu_thi_v1/src/Template/Element/cart.ctp
<?= $this->Html->link(
'<span class="cart">$ 99.54</span><span class="check">KIỂM TRA GIỎ HÀNG</span>'
,'/home/gio-hang',['escape'=>false]) ?>
<?php if($this->request->session()->check('cart')){
		echo 
		'<div class="shopping">
		<p>------------------------------------------------------------------</p>
	    <h5>Click vào Kiểm Tra Giỏ Hàng </h5>
	    <p>Bạn có 2 sản phẩm trong giỏ hàng</p>
		</div>';

	}else{
		echo 
		'<div class="shopping">
	    <h5>Your Shopping Cart is empty.</h5>
	    <p>Give it purpose—fill it with books, movies, mobiles, cameras, toys and fashion jewellery.</p>
		</div>';
		} ?>

sieu_thi_v1/src/Template/Element/cart_cosp.ctp
<?php $cart_products = $this->request->session()->read('cart'); ?>
<!-- container -->
<div class="container">
<div class="container text-center">
			<div class="col-md-5 col-sm-12">
				<div class="bigcart"></div>
				<h1>Your shopping cart</h1>
			</div>
			
			<div class="col-md-7 col-sm-12 text-left">
				<ul>
					<li class="row list-inline columnCaptions">
						<span class="stt">STT</span>
						<span class="itemName">TÊN SẢN PHẨM</span>
						<span class="quantity">SL</span>
						<span class="price_cart">GIÁ SẢN PHẨM</span>
					</li>
					<?php foreach($cart_products as $products): ?>
					<li class="row">
						<span class="stt">1</span>
						<span class="itemName"><?= $products['title'];?></span>
						<span class="quantity"><input type="text" name="quantity" value="<?= $products['quantity'];?>"></span>
						<span class="delete"><a href="<?= $products['id'];?>">XÓA</a></span>
						<span class="price_cart"><?= $products['price'];?></span>
					</li>
					<?php endforeach ; ?>
					<li class="row totals">
						<span class="itemName">Total:</span>
						<span class="price_total">$1694.43</span>
						<span class="order"> <a class="text-center">ORDER</a></span>
					</li>
				</ul>
			</div>

		</div>

		<!-- The popover content -->
		<!-- JavaScript includes -->

		<!-- <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script> -->
		<?php echo $this->Html->script('home/jquery-1.11.0.min'); ?> 
		<?php echo $this->Html->script('home/customjs'); ?>
		<!-- <script src="assets/js/bootstrap.min.js"></script> -->
		<?php echo $this->Html->script('home/bootstrap.min'); ?>
		<!-- <script src="assets/js/customjs.js"></script> -->
</div>
<!-- container -->

sieu_thi_v1/src/Template/Element/cart_item1.ctp
<div class="container">
	<h3>Cart Empty</h3>
	<p>Lorem ipsum dolor sit amet enim. Etiam ullamcorp uspendisse a pellentesque.
		Etiam ullamcorp uspendisse a pellentesque.Lorem ipsum dolor sit amet enim.
		Your Bascket Is Empty Please Go <a href="men.html">here</a> And Shop
	</p>
</div>

sieu_thi_v1/src/Template/Element/categories.ctp
<div class="categories">
	<h3>DANH MỤC</h3>
	<ul>
	<?php foreach ($query2 as $value): ?>
		<li><?php echo $this->Html->link($value['name'],'/home/'.$value['slug']); ?></li>
	<?php endforeach; ?>
	</ul>
	</div>
</div>

sieu_thi_v1/src/Template/Element/footer.ctp
<!-- footer -->
<div class="footer">
	<!-- container -->
	<div class="container">
		<div class="col-md-3 stores-grid">
			<div class="stores">
				<h3>Our Stores</h3>
				<ul>
					<li>Feel free to visit our stores or contact us.</li>
					<li>1401 South Grand Avenue </li>
					<li>Los Angeles, CA 90015 </li>
					<li>(213) 748-2411</li>

					<span>
					<li class="drive">100 Fairview Drive </li>
					<li>Franklin, VA 23851</li> 
					<li>(757) 569-6100 </li>
					</span>
				</ul>
			</div>
			<div class="social-icons white-icons">
				<ul>
					<li><a href="#" class="facebook"></a></li>
					<li><a href="#" class="twitter"></a></li>
					<li><a href="#" class="chrome"></a></li>
					<li><a href="#" class="vimeo"></a></li>
					<li><a href="#" class="rss"></a></li>
			</div>
		</div>
		<div class="col-md-3 blog">
			<h3>Blog posts</h3>
			<a href="#">Justin Bieber confirmed that he is gay.</a>
			<p>Lorem ipsum dolor sit amet, consectetur
				adipiscing elit. Donec sed auctor elit.
			</p>
			<a href="#">New sexy sport clothes are here!</a>
			<p>Lorem ipsum dolor sit amet, consectetur
				adipiscing elit. Donec sed auctor elit.
			</p>
			<a href="#">Summer sales are coming!</a>
			<p>Lorem ipsum dolor sit amet, consectetur
				adipiscing elit. Donec sed auctor elit.
			</p>
		</div>
		<div class="col-md-3 support">
			<h3>Support</h3>
			<div class="support-grids">
				<div class="support-left">
					<ul>
						<li><a href="#">Terms & Conditions</a></li>
						<li><a href="#">FAQ</a></li>
						<li><a href="#">Payment</a></li>
						<li><a href="#">Refunds</a></li>
						<li><a href="#">Track Order</a></li>
						<li><a href="#">Services</a></li>
						<li><a href="#">Privacy & Security</a></li>
						<li><a href="#">Careers</a></li>
						<li><a href="#">Press</a></li>
						<li><a href="#">Corporate Information</a></li>
					</ul>
				</div>
				<div class="support-left support-right">
					<ul>
						<li><a href="#">Sizing</a></li>
						<li><a href="#">Ordering</a></li>
						<li><a href="#">Shipping</a></li>
						<li><a href="#">Return Policy</a></li>
						<li><a href="#">Affiliates</a></li>
						<li><a href="#">Find A Store </a></li>
						<li><a href="#">Site Map</a></li>
						<li><a href="#">Sign Up & Save</a></li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="col-md-3 contact">
			<h3>Contact us</h3>
			<form>
				<input type="text" value="your e-mail..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'your e-mail...';}" required="">
				<textarea value="your text...:" onfocus="if(this.value == 'your text...') this.value='';" onblur="if(this.value == '') this.value='your text...';">your text...</textarea>
				<input type="submit" value="Send MESSAGE">
			</form>
		</div>
		<div class="clearfix"> </div>
		<div class="copyright">
			<p>Template by <a href="http://w3layouts.com/">W3layouts</a></p>
		</p>
	</div>
	<!-- // container -->
</div>
<!-- //footer -->

sieu_thi_v1/src/Template/Element/login.ctp
<!-- pop-up-box -->
<!-- <script type="text/javascript" src="js/modernizr.custom.min.js"></script> -->
<?php echo $this->Html->script('home/modernizr.custom.min'); ?>    
<!-- <link href="css/popuo-box.css" rel="stylesheet" type="text/css" media="all" /> -->
<?php echo $this->Html->css('home/popuo-box'); ?>
<!-- <script src="js/jquery.magnific-popup.js" type="text/javascript"></script> -->
<?php echo $this->Html->script('home/jquery.magnific-popup'); ?>
<!--//pop-up-box -->
<div id="small-dialog2" class="mfp-hide">
	<h3>Create Account</h3> 
	<div class="social-sits">
		<ul>
			<li><a class="fb" href="#">Connect with Facebook</a></li>
			<li><a class="fb google" href="#">Connect with Google</a></li>
		</ul>
	</div>
	<div class="signup">
		<form>
			<input type="text" class="email" placeholder="Email" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?" />
			<input type="password" placeholder="Password" required="required" pattern=".{6,}" title="Minimum 6 characters required" autocomplete="off" />
			<input type="text" class="email" placeholder="Mobile Number" maxlength="10" pattern="[1-9]{1}\d{9}" title="Enter a valid mobile number" />
			<input type="submit"  value="Sign In"/>
		</form>
	</div>
	<div class="clearfix"> </div>
</div>	
<script>
	$(document).ready(function() {
		$('.popup-with-zoom-anim').magnificPopup({
			type: 'inline',
			fixedContentPos: false,
			fixedBgPos: true,
			overflowY: 'auto',
			closeBtnInside: true,
			preloader: false,
			midClick: true,
			removalDelay: 300,
			mainClass: 'my-mfp-zoom-in'
		});
		
	});
</script>	

sieu_thi_v1/src/Template/Element/products.ctp
<?php foreach ($query as $value):?>
<div class="col-md-3 fashion-grid">
	<a href="#"><?php echo $this->Html->image($value['avatar'],['width'=>'276','height'=>'276']); ?>
		<div class="product">
			<h3><?php echo $value['name'] ?></h3>
			<p><span></span> <?php echo $this->Number->format($value['price_out'],['places' => 2,'after'=> ' VNĐ']); ?></p>	 
		</div>							 
	</a>
	<div class="fashion-view"><span></span>
		<div class="clearfix"></div>
		<h4>
			<?= $value->has('category') ? $this->Html->link('Chi Tiết','/home/'.$value->category->slug.'/'.$value['id']) : '' ?>
		</h4>
	</div>
</div>
<?php endforeach ; ?>